##########################################
## Uninstall ambari server on all nodes
##########################################

- name: stop ambari-server service
  shell: "bash ambari-server stop"
  ignore_errors: yes
  when: (inventory_hostname in groups['master'])

- name: stop ambari-agent service
  shell: "bash ambari-agent stop"
  ignore_errors: yes

- name: run uninstall script on all nodes
  shell: python /usr/lib/python2.6/site-packages/ambari_commons/host_uninstall.py
  ignore_errors: yes

- name: remove ambari agent on all nodes
  yum:
    name: ambari-agent
    state: removed

- name: remove remaining config files on all nodes
  shell:
     rm -rf /etc/yum.repos.d/IOP.repo
     rm -rf /etc/yum.repos.d/IOP-UTILS.repo
     rm -rf /etc/yum.repos.d/ambari.repo
     rm -rf /var/log/ambari-agent
     rm -rf /var/log/knox
     rm -rf /etc/ambari-agent
  ignore_errors: yes

- name: remove ambari server on master node
  yum:
    name: ambari-server
    state: removed
  when: (inventory_hostname in groups['master'])

- name: remove remaining ambari server on master node
  shell:
    rm -rf /etc/ambari-server
    rm -rf /var/log/ambari-server/
    su - postgres -c "dropdb ambari"
    su - postgres -c "dropdb ambarirca"
  ignore_errors: yes
  when: (inventory_hostname in groups['master'])

- name: remove postgress on master node
  yum:
    name: postgresql
    state: removed
  when: (inventory_hostname in groups['master'])

- user: name="ambari-qa" state="absent" remove="yes"
- user: name="yarn" state="absent" remove="yes"
- user: name="hdfs" state="absent" remove="yes"
- user: name="users" state="absent" remove="yes"
- user: name="hcat" state="absent" remove="yes"
- user: name="hive" state="absent" remove="yes"
- user: name="mapred" state="absent" remove="yes"
- user: name="hadoop" state="absent" remove="yes"
- user: name="spark" state="absent" remove="yes"
- user: name="knox" state="absent" remove="yes"
- user: name="zookeeper" state="absent" remove="yes"
