- name: spark setup
  hosts: all
  remote_user: root
  roles:
    - role: common
    - role: hdfs
    - role: spark
#    - role: elasticsearch

- name: notebook platform
  hosts: all
  remote_user: root
  roles:
   - role: anaconda
   - role: notebook

