- name: install common dependencies
  hosts: all
  remote_user: root
  roles:
    - role: common

- name: ambari setup
  hosts: all
  remote_user: root
  roles:
    - role: iop

- name: anaconda
  hosts: all
  vars:
    anaconda:
      update_path: false
  remote_user: root
  roles:
   - role: anaconda

- name: notebook platform dependencies
  hosts: all
  vars:
    notebook:
      use_anaconda: true
  remote_user: root
  roles:
    - role: notebook