- name: spark setup
  hosts: all
  remote_user: root
  roles:
    - role: common
    - role: zookeeper
    - role: kafka
    - role: hdfs
    - role: spark
    - role: spark-cluster-admin
#    - role: elasticsearch

#- name: notebook platform
#  hosts: all
#  remote_user: root
#  roles:
#   - role: anaconda
#   - role: notebook

