- name: spark setup
  hosts: nodes
  remote_user: root

  roles:
    - role: common
    - role: hdfs
    - role: spark

- name: notebook setup
  hosts: master
  remote_user: root

  roles:
    - role: anaconda
