notebook:

  gateway_version: 1.1.1

  gateway_install_directory: "{{ install_dir }}/gateway"
  gateway_log_directory: "{{ install_dir }}/gateway/log"
  gateway_runtime_directory: "{{ install_dir }}/gateway/runtime"

  toree_archive_package_name: toree-0.3.0.tar.gz
  toree_pip_download_location: https://dist.apache.org/repos/dist/release/incubator/toree/0.3.0-incubating/toree-pip/

  yarn_endpoint_host: "{{ groups['master'][0] }}.{{ ansible_domain }}"

  #"lookup('env', 'SPARK_HOME') | default('/usr/hdp/current/spark2-client', true)"
  spark_home: /usr/hdp/current/spark2-client

  user: gateway
  home_dir: /home/gateway
  groups: [hdfs, users]

  #use_anaconda
  deploy_kernelspecs_to_workers: false
