internal:
  elyra_install_dir: "{{ install_dir }}/elyra"

notebook:

  elyra_version: 1.0.1

  elyra_install_directory: "{{ internal.elyra_install_dir }}"
  elyra_log_directory: "{{ internal.elyra_install_dir }}/log"
  elyra_runtime_directory: "{{ internal.elyra_install_dir }}/runtime"

  toree_archive_package_name: toree-0.2.0.tar.gz
  toree_pip_download_location: https://dist.apache.org/repos/dist/release/incubator/toree/0.2.0-incubating/toree-pip/

  yarn_endpoint_host: "{{ groups['master'][0] }}"

  #"lookup('env', 'SPARK_HOME') | default('/usr/hdp/current/spark2-client', true)"
  spark_home: /usr/hdp/current/spark2-client

  user: elyra
  home_dir: /home/elyra
  groups: [hdfs, users]

  #use_anaconda
  enable_impersonation: false
  enable_kerberos: false
  deploy_kernelspecs_to_workers: false
