
- name: install commonly used os dependencies
  yum:
    name: gcc,openssl-devel,libffi-devel,python-devel
    state: installed

- name: upgrade all packages
  yum: name=* state=latest

- name: clean yum repository
  shell: "yum clean all"