- name: install commonly used os dependencies
  yum:
    name: bzip2,gcc,openssl-devel,libffi-devel,python-devel,openssl-devel,libcurl,libcurl-devel
    state: installed

- name: upgrade all packages
  yum: name=* state=latest

- name: clean yum repository
  shell: "yum clean all"